class LookupType:
    TARGET_OBJECT = "target_object"
    TARGET_GROUP = "target_group"
    N_TERMINUS = "n_terminus"
    C_TERMINUS = "c_terminus"
    SYNTHESIS = "synthesis_type"
    COMPLEXITY = "complexity"
    KINGDOM = "kingdom"
    INTRA_CHAIN_BOND = "intra_chain_bond"
    INTER_CHAIN_BOND = "inter_chain_bond"
    UNUSUAL_AMINO_ACID = "unusual_amino_acid"
    UNIT = "unit"
    ACTIVITY_MEASURE = "activity_measure"
    AUTHOR = "author"
    JOURNAL = "journal"
    TARGET_ACTIVITY = "target_species"
    TARGET_CELL = "mammalian_cell"
    MEDIUM = "medium";